import { useMemo, useState } from 'react'
import { useAuth } from '../../context/AuthContext.jsx'
import Button from '../../components/ui/Button.jsx'

const initialTenants = [{ id: 1, name: 'Mame Diop', unit: 'Appartement 2A', rent: 250000, status: 'Payé' }, { id: 2, name: 'Samba Ndiaye', unit: 'Appartement 3B', rent: 180000, status: 'En retard' }, { id: 3, name: 'Aïssatou Fall', unit: 'Studio 1', rent: 320000, status: 'À relancer' }]
const money = (amount) => `${new Intl.NumberFormat('fr-SN').format(amount)} F`

export default function DashboardPage() {
  const { agency, logout } = useAuth(); const [tenants, setTenants] = useState(initialTenants); const [tab, setTab] = useState('Vue d’ensemble'); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ name: '', unit: '', rent: '' })
  const totals = useMemo(() => ({ expected: tenants.reduce((sum, tenant) => sum + tenant.rent, 0), collected: tenants.filter((tenant) => tenant.status === 'Payé').reduce((sum, tenant) => sum + tenant.rent, 0), late: tenants.filter((tenant) => tenant.status === 'En retard').length }), [tenants])
  function addTenant(event) { event.preventDefault(); if (!form.name || !form.unit || !Number(form.rent)) return; setTenants([...tenants, { ...form, id: Date.now(), rent: Number(form.rent), status: 'À relancer' }]); setForm({ name: '', unit: '', rent: '' }); setShowForm(false) }
  return <div className="dashboard"><aside><div><p className="brand"><span>Kër</span>guiPa</p><p className="agency-name">{agency.agencyName}</p><span className="plan">PLAN DÉMARRAGE</span></div><nav>{['Vue d’ensemble', 'Locataires', 'Encaissements', 'Relances'].map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav><div className="profile"><b>{agency.agencyName.slice(0, 2).toUpperCase()}</b><div><strong>{agency.agencyName}</strong><button onClick={logout}>Se déconnecter</button></div></div></aside><main><header className="dashboard-header"><div><p className="eyebrow">BONJOUR, {agency.agencyName.toUpperCase()}</p><h1>{tab}</h1><p>Voici le suivi de votre agence pour ce mois.</p></div><Button onClick={() => setShowForm(true)}>+ Ajouter un locataire</Button></header><section className="stat-grid"><article><span>Total attendu</span><strong>{money(totals.expected)}</strong></article><article><span>Collecté</span><strong className="success">{money(totals.collected)}</strong></article><article><span>Impayés</span><strong className="accent">{money(totals.expected - totals.collected)}</strong></article><article><span>En retard</span><strong className="danger">{totals.late} locataire{totals.late > 1 ? 's' : ''}</strong></article></section><section className="tenant-panel"><div><h2>Locataires à suivre</h2><p>Échéances et statut des paiements.</p></div><div className="tenant-table"><div className="row table-head"><span>Locataire</span><span>Logement</span><span>Loyer</span><span>Statut</span></div>{tenants.map((tenant) => <div className="row" key={tenant.id}><b>{tenant.name}</b><span>{tenant.unit}</span><span>{money(tenant.rent)}</span><i className={tenant.status === 'Payé' ? 'paid' : tenant.status === 'En retard' ? 'late' : 'pending'}>{tenant.status}</i></div>)}</div></section></main>{showForm && <div className="modal"><form onSubmit={addTenant}><button type="button" className="close" onClick={() => setShowForm(false)}>×</button><p className="eyebrow">NOUVEAU LOCATAIRE</p><h2>Ajouter un locataire</h2><label>Nom complet<input autoFocus value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Logement<input value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })} placeholder="Ex. Appartement 2A" /></label><label>Loyer mensuel (F CFA)<input type="number" min="1" value={form.rent} onChange={(e) => setForm({ ...form, rent: e.target.value })} /></label><Button type="submit">Ajouter</Button></form></div>}</div>
}
