import { Link } from 'react-router-dom'
import PublicHeader from '../../widgets/public-header/PublicHeader.jsx'

const features = [
  { icon: '↗', title: 'Encaissements centralisés', text: 'Suivez chaque paiement, quel que soit le bien ou le locataire.' },
  { icon: '◌', title: 'Relances au bon moment', text: 'Prévenez les retards avec des rappels simples et personnalisés.' },
  { icon: '◫', title: 'Vision financière nette', text: 'Visualisez les recettes attendues, reçues et à relancer.' },
]
const testimonials = [
  ['“Enfin un outil clair pour garder le fil de nos paiements.”', 'Aminata Ndiaye', 'Gérante, Dakar'],
  ['“On sait qui relancer et à quel moment, sans ouvrir dix fichiers.”', 'Cheikh Fall', 'Agence immobilière, Thiès'],
]

export default function HomePage() {
  return <div className="landing"><PublicHeader /><main>
    <section className="landing-hero"><div className="hero-copy"><div className="product-pill"><span></span> La gestion locative, simplifiée</div><h1>Pilotez vos loyers.<br /><em>Gardez l’esprit libre.</em></h1><p>Le tableau de bord pensé pour les agences immobilières qui veulent suivre leurs encaissements sans perdre de temps.</p><div className="hero-actions"><Link className="button landing-primary" to="/register">Démarrer gratuitement <b>→</b></Link><a className="landing-video" href="#fonctionnalites"><i>▶</i> Voir comment ça marche</a></div><div className="hero-social-proof"><div className="avatar-stack"><span>MA</span><span>CN</span><span>AF</span><span>+</span></div><p><b>100+ professionnels</b><br />organisent déjà leurs loyers.</p></div></div><div className="hero-dashboard" aria-label="Aperçu du tableau de bord"><div className="dashboard-window"><div className="window-top"><div className="mini-brand"><b>Kër</b>guiPa</div><div className="window-dots"><i></i><i></i><i></i></div></div><div className="preview-shell"><aside><span className="preview-avatar">TI</span><small>Teranga Immo</small><div className="preview-nav active">▦ <b>Vue d’ensemble</b></div><div className="preview-nav">◌ Locataires</div><div className="preview-nav">⌁ Paiements</div><div className="preview-nav">✦ Relances</div></aside><section><p className="preview-overline">VENDREDI, 31 JUILLET</p><h2>Bonjour, Teranga <span>✦</span></h2><div className="preview-stats"><article><small>Collecté ce mois</small><b>4 850 000 <em>F</em></b><span>↗ 12,5%</span></article><article><small>À relancer</small><b>8 <em>locataires</em></b><span className="orange">Action requise</span></article></div><div className="preview-chart"><div><b>Encaissements</b><small>6 derniers mois</small></div><div className="chart-bars"><i></i><i></i><i></i><i></i><i></i><i></i></div></div></section></div></div><div className="float-card float-card--payment"><span>✓</span><div><small>Paiement reçu</small><b>250 000 F</b></div></div><div className="float-card float-card--late"><span>!</span><div><small>Relance envoyée</small><b>Appartement 3B</b></div></div></div></section>
    <section className="trusted"><p>CONÇU POUR LES PROFESSIONNELS DE L’IMMOBILIER</p><div><span>TERANGA <i>IMMOBILIER</i></span><span>DAKAR <b>HABITAT</b></span><span>◈ SENIMMO</span><span>KAAY <i>AGENCE</i></span></div></section>
    <section id="fonctionnalites" className="landing-features"><div className="section-intro"><p className="eyebrow">UN SEUL ESPACE, TOUTE L’AGENCE</p><h2>Moins de suivi manuel.<br /><em>Plus de visibilité.</em></h2><p>KërguiPa réunit les informations utiles de votre portefeuille pour vous aider à agir, au bon moment.</p></div><div className="feature-cards">{features.map((feature, index) => <article key={feature.title} className={`feature-card feature-card--${index + 1}`}><span className="feature-icon">{feature.icon}</span><p className="feature-number">0{index + 1}</p><h3>{feature.title}</h3><p>{feature.text}</p><a href="#tarifs">Découvrir <b>→</b></a></article>)}</div></section>
    <section className="workflow"><div className="workflow-visual"><div className="workflow-card"><span className="workflow-logo">K</span><p>Un échéancier<br /><b>toujours à jour.</b></p><div className="calendar-lines"><i></i><i></i><i></i><i></i><i></i></div></div></div><div className="workflow-copy"><p className="eyebrow">RESTEZ EN AVANCE</p><h2>Chaque échéance<br />devient une <em>opportunité.</em></h2><p>Des rappels structurés avant et après l’échéance vous donnent le bon contexte pour échanger avec chaque locataire.</p><ul><li><i>✓</i> Échéances visibles en un coup d’œil</li><li><i>✓</i> Retards identifiés automatiquement</li><li><i>✓</i> Historique prêt pour vos rapports</li></ul><Link className="text-cta" to="/register">Créer mon espace agence <b>→</b></Link></div></section>
    <section id="temoignages" className="testimonials"><p className="eyebrow">ILS ONT CHOISI LA SIMPLICITÉ</p><h2>Des équipes plus sereines.</h2><div>{testimonials.map(([quote, name, role]) => <article key={name}><div className="quote-mark">“</div><blockquote>{quote}</blockquote><footer><span>{name.split(' ').map((item) => item[0]).join('')}</span><p><b>{name}</b><small>{role}</small></p></footer></article>)}</div></section>
    <section id="tarifs" className="landing-cta"><div><p className="eyebrow">PRÊT À MIEUX PILOTER ?</p><h2>Vos loyers méritent<br />mieux qu’un tableur.</h2><p>Commencez aujourd’hui, gratuitement. Aucun engagement, aucune carte requise.</p><Link className="button landing-primary" to="/register">Créer mon compte agence <b>→</b></Link></div><div className="cta-orb"><span>✦</span></div></section>
  </main><footer className="landing-footer"><span className="brand"><i>Kër</i>guiPa</span><p>La gestion locative, enfin fluide.</p><div><a href="#fonctionnalites">Fonctionnalités</a><a href="#tarifs">Tarifs</a><Link to="/login">Connexion</Link></div></footer></div>
}
