import { getDueStatus } from '../../../shared/lib/dates.js'
import { formatCfa } from '../../../shared/lib/formatters.js'

const activities = [
  ['Paiement enregistré', 'Mame Diop · Appartement 2A', '250 000 F', 'success', 'Il y a 18 min'],
  ['Relance programmée', 'Samba Ndiaye · Appartement 3B', 'Échéance dépassée', 'warning', 'Il y a 2 h'],
  ['Nouveau locataire', 'Aïssatou Fall · Studio 1', 'À valider', 'neutral', 'Hier'],
]

export default function DashboardInsights({ tenants, metrics }) {
  const priorityTenants = tenants.filter((tenant) => getDueStatus(tenant.dueDate, tenant.status).tone !== 'paid').slice(0, 3)
  return <section className="dashboard-insights"><article className="priority-card"><header><div><p className="panel-kicker">À TRAITER AUJOURD’HUI</p><h2>Actions prioritaires</h2></div><span className="priority-count">{priorityTenants.length}</span></header><div className="priority-list">{priorityTenants.length ? priorityTenants.map((tenant) => { const status = getDueStatus(tenant.dueDate, tenant.status); return <div key={tenant.id} className="priority-item"><span className={`priority-dot priority-dot--${status.tone}`}></span><div><b>{tenant.name}</b><small>{tenant.unit} · {formatCfa(tenant.rent)}</small></div><em className={status.tone}>{status.label}</em></div> }) : <p className="empty-state">Tout est à jour. Très bon travail !</p>}</div><button className="panel-link" type="button">Voir toutes les relances <b>→</b></button></article><article className="activity-card"><header><div><p className="panel-kicker">DERNIÈRES MISES À JOUR</p><h2>Activité récente</h2></div><button type="button" aria-label="Options d'activité">•••</button></header><div className="activity-list">{activities.map(([title, detail, amount, tone, date]) => <div className="activity-row" key={title}><span className={`activity-icon activity-icon--${tone}`}>{tone === 'success' ? '✓' : tone === 'warning' ? '!' : '+'}</span><div><b>{title}</b><small>{detail}</small></div><div><strong>{amount}</strong><time>{date}</time></div></div>)}</div></article><article className="performance-card"><p className="panel-kicker">PERFORMANCE DU MOIS</p><div className="performance-main"><div className="performance-ring" style={{ '--progress': `${metrics.collectionRate * 3.6}deg` }}><span>{metrics.collectionRate}%</span></div><div><h2>Objectif mensuel</h2><p>{formatCfa(metrics.collected)} collectés sur {formatCfa(metrics.expected)}</p></div></div><div className="performance-scale"><span>0%</span><div><i style={{ width: `${metrics.collectionRate}%` }}></i></div><span>100%</span></div><p className="performance-note">{metrics.collectionRate >= 75 ? 'Votre collecte progresse correctement ce mois-ci.' : 'Quelques relances peuvent encore améliorer ce résultat.'}</p></article></section>
}
